<?php

namespace AppBundle\Repository;

/**
 * ManufactureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ManufactureRepository extends \Doctrine\ORM\EntityRepository
{
}
