# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    appbundle.admin.blog:
        class: AppBundle\Admin\BlogAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Blog, label: "Posts" }
        arguments:
            - ~
            - AppBundle\Entity\Blog
            - 'AppBundle:BlogAdmin'
    appbundle.admin.tags:
        class: AppBundle\Admin\TagsAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Tags for posts, label: "Tag name" }
        arguments:
            - ~
            - AppBundle\Entity\Tags
            - 'AppBundle:TagsAdmin'
    appbundle.admin.categories:
        class: AppBundle\Admin\CategoryAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Category for products, label: "Category name" }
        arguments:
            - ~
            - AppBundle\Entity\Category
            - 'AppBundle:CategoryAdmin'
    appbundle.admin.manufactures:
        class: AppBundle\Admin\ManufactureAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Manufacture for products, label: "Manufacture name" }
        arguments:
            - ~
            - AppBundle\Entity\Manufacture
            - 'AppBundle:ManufactureAdmin'
    appbundle.admin.product:
        class: AppBundle\Admin\ProductAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Products, label: "Products" }
        arguments:
            - ~
            - AppBundle\Entity\Product
            - 'AppBundle:ProductAdmin'